import Foundation
import AppKit
import SwiftData

public enum ShareServiceError: Error {
    case notImplemented
    case exportError(String)
    case invalidData
}

/// Service for sharing productivity analytics via multiple channels
@MainActor
public final class ShareService {
    public static let shared = ShareService()

    private init() {}

    // MARK: - Text Summary Generation

    /// Generate a human-readable text summary of analytics
    public func generateTextSummary(
        appUsageStats: [AppUsageStat],
        focusScore: Double,
        productiveSeconds: Int,
        distractingSeconds: Int,
        neutralSeconds: Int,
        totalSeconds: Int,
        gitCommitsCount: Int,
        timeFilter: TimeFilter,
        selectedDate: Date,
        achievements: [Achievement]? = nil
    ) -> String {
        var summary = ""

        // Header with emoji
        summary += "📊 Productivity Report\n"
        summary += "━━━━━━━━━━━━━━━━━━━━━━\n\n"

        // Date range
        let (startDate, endDate) = timeFilter.dateRange(from: selectedDate)
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium

        summary += "📅 Period: \(timeFilter.rawValue)\n"
        if timeFilter == .day {
            summary += "   \(dateFormatter.string(from: startDate))\n"
        } else {
            summary += "   \(dateFormatter.string(from: startDate)) - \(dateFormatter.string(from: endDate))\n"
        }
        summary += "\n"

        // Focus Score with description
        summary += "🎯 Focus Score: \(String(format: "%.0f", focusScore))/100\n"
        summary += "   \(focusScoreDescription(focusScore))\n\n"

        // Screen time breakdown
        summary += "⏱️  Screen Time Breakdown:\n"
        summary += "   Productive:   \(formatDuration(productiveSeconds)) (\(percentage(productiveSeconds, of: totalSeconds))%)\n"
        summary += "   Neutral:      \(formatDuration(neutralSeconds)) (\(percentage(neutralSeconds, of: totalSeconds))%)\n"
        summary += "   Distracting:  \(formatDuration(distractingSeconds)) (\(percentage(distractingSeconds, of: totalSeconds))%)\n"
        summary += "   Total:        \(formatDuration(totalSeconds))\n\n"

        // Top 5 apps
        summary += "🏆 Top 5 Apps:\n"
        let topApps = Array(appUsageStats.prefix(5))
        if topApps.isEmpty {
            summary += "   No activity recorded\n"
        } else {
            for (index, stat) in topApps.enumerated() {
                let rank = ["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣"][index]
                summary += "   \(rank) \(stat.appName) - \(stat.formattedDuration)\n"
            }
        }
        summary += "\n"

        // Git activity
        if gitCommitsCount > 0 {
            summary += "💻 Git Activity:\n"
            summary += "   \(gitCommitsCount) commit\(gitCommitsCount == 1 ? "" : "s") pushed\n\n"
        }

        // Achievements (if provided)
        if let achievements = achievements, !achievements.isEmpty {
            let unlockedAchievements = achievements.filter { $0.isUnlocked }
            if !unlockedAchievements.isEmpty {
                summary += "🏅 Achievements Unlocked: \(unlockedAchievements.count)\n"
                for achievement in unlockedAchievements.prefix(3) {
                    summary += "   • \(achievement.type.displayName)\n"
                }
                if unlockedAchievements.count > 3 {
                    summary += "   ...and \(unlockedAchievements.count - 3) more\n"
                }
                summary += "\n"
            }
        }

        // Footer
        summary += "━━━━━━━━━━━━━━━━━━━━━━\n"
        summary += "Generated by Kafeel • \(Date().formatted(date: .abbreviated, time: .shortened))"

        return summary
    }

    // MARK: - JSON Export

    /// Generate a JSON export of analytics data
    public func generateJSONExport(
        appUsageStats: [AppUsageStat],
        focusScore: Double,
        productiveSeconds: Int,
        distractingSeconds: Int,
        neutralSeconds: Int,
        totalSeconds: Int,
        gitCommitsCount: Int,
        timeFilter: TimeFilter,
        selectedDate: Date,
        activities: [ActivityLog] = [],
        gitActivities: [GitActivity] = []
    ) throws -> Data {
        let (startDate, endDate) = timeFilter.dateRange(from: selectedDate)

        let exportData: [String: Any] = [
            "metadata": [
                "exported_at": ISO8601DateFormatter().string(from: Date()),
                "period": timeFilter.rawValue,
                "start_date": ISO8601DateFormatter().string(from: startDate),
                "end_date": ISO8601DateFormatter().string(from: endDate),
                "version": "1.0"
            ],
            "summary": [
                "focus_score": focusScore,
                "total_seconds": totalSeconds,
                "productive_seconds": productiveSeconds,
                "neutral_seconds": neutralSeconds,
                "distracting_seconds": distractingSeconds,
                "git_commits_count": gitCommitsCount
            ],
            "app_usage": appUsageStats.map { stat in
                [
                    "bundle_identifier": stat.bundleIdentifier,
                    "app_name": stat.appName,
                    "total_seconds": stat.totalSeconds,
                    "formatted_duration": stat.formattedDuration
                ]
            },
            "activities": activities.map { activity in
                [
                    "app_bundle_identifier": activity.appBundleIdentifier,
                    "app_name": activity.appName,
                    "window_title": activity.windowTitle ?? "",
                    "start_time": ISO8601DateFormatter().string(from: activity.startTime),
                    "duration_seconds": activity.durationSeconds
                ]
            },
            "git_activity": gitActivities.map { git in
                [
                    "commit_hash": git.commitHash,
                    "message": git.message,
                    "author": git.author,
                    "date": ISO8601DateFormatter().string(from: git.date),
                    "repository_name": git.repositoryName,
                    "additions": git.additions,
                    "deletions": git.deletions,
                    "files_changed": git.filesChanged
                ]
            }
        ]

        return try JSONSerialization.data(withJSONObject: exportData, options: [.prettyPrinted, .sortedKeys])
    }

    // MARK: - Clipboard

    /// Copy text to clipboard
    public func copyToClipboard(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // MARK: - Share Sheet

    /// Show macOS share sheet with items
    public func showShareSheet(items: [Any], from view: NSView) {
        let picker = NSSharingServicePicker(items: items)

        // Calculate position relative to view
        let bounds = view.bounds
        let rect = NSRect(x: bounds.midX, y: bounds.midY, width: 1, height: 1)

        picker.show(relativeTo: rect, of: view, preferredEdge: .minY)
    }

    // MARK: - Email

    /// Open Mail.app with pre-filled content
    public func shareViaEmail(summary: String, subject: String = "My Productivity Report") {
        // Encode email content
        guard let encodedSubject = subject.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
              let encodedBody = summary.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed),
              let mailtoURL = URL(string: "mailto:?subject=\(encodedSubject)&body=\(encodedBody)") else {
            print("Failed to create mailto URL")
            return
        }

        NSWorkspace.shared.open(mailtoURL)
    }

    // MARK: - File Export

    /// Save JSON export to file
    public func exportToFile(data: Data, filename: String) -> URL? {
        let savePanel = NSSavePanel()
        savePanel.allowedContentTypes = [.json]
        savePanel.canCreateDirectories = true
        savePanel.isExtensionHidden = false
        savePanel.title = "Export Analytics Data"
        savePanel.message = "Choose a location to save your analytics data"
        savePanel.nameFieldStringValue = filename

        guard savePanel.runModal() == .OK, let url = savePanel.url else {
            return nil
        }

        do {
            try data.write(to: url, options: .atomic)
            return url
        } catch {
            print("Failed to save file: \(error)")
            return nil
        }
    }

    // MARK: - Private Helpers

    private func focusScoreDescription(_ score: Double) -> String {
        switch score {
        case 90...:
            return "Exceptional focus! You're in the zone."
        case 75..<90:
            return "Great productivity! Keep it up."
        case 60..<75:
            return "Good focus with room for improvement."
        case 40..<60:
            return "Moderate productivity. Try to minimize distractions."
        case 20..<40:
            return "Below average focus. Consider reviewing your habits."
        default:
            return "Low productivity. Time to refocus!"
        }
    }

    private func formatDuration(_ seconds: Int) -> String {
        let hours = seconds / 3600
        let minutes = (seconds % 3600) / 60

        if hours > 0 {
            return "\(hours)h \(minutes)m"
        } else if minutes > 0 {
            return "\(minutes)m"
        } else {
            return "\(seconds)s"
        }
    }

    private func percentage(_ value: Int, of total: Int) -> Int {
        guard total > 0 else { return 0 }
        return Int(Double(value) / Double(total) * 100)
    }
}
